language: java
script:
     - set -e
     - mkdir -p out
     - SRCS=$(find * -type f -name '*.java')
     - JARS=$(find * -name "*.jar" |  paste -sd ':' -)
     - for SRC in $SRCS; do echo Compiling $SRC; javac -cp $JARS -sourcepath src -d out $SRC; done;
