/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewGUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ListCellRenderer;
import javax.swing.*;

import GUI.AddNote;
import GUI.UserPresentation;
import GUI.UserProfile;
import GUI.ViewStudentsInClass;
import NotezzaClient.NotezzaClient;
import NotezzaServer.Command;
import NotezzaServer.CommandType;
import objects.*;

/**
 *
 * @author user
 */
public class MainWin extends javax.swing.JFrame {
    private NotezzaClient client;
    private CourseList courseList;
    private Vector<Course> courses;
    private Course currentCourse;
    private Note currentNote;

    private Vector<Note> displayedNotes;
    private DefaultListModel<String> notesOverviewModel;
    /**
     * Creates new form MainWin
     */
    public MainWin(NotezzaClient client, CourseList courseList) {
        this.client = client;
        this.courseList = courseList;
        initComponents();
        initContent();
    }

    private void initContent() {
        if (courseList == null || courseList.getCourses() == null || courseList.getCourses().isEmpty()) {
            // No course available

            // classes dropdown box
            classes.setModel(new javax.swing.DefaultComboBoxModel<>(new String [] {"No Classes"}));
            classes.setToolTipText("Change Class");
            // Posts Overview
            overviewList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "<html><h3>No Posts Available<h3><html>" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });

            // post Content
            this.post.setText("<html><body style='background-color:#f0f8ff;'>"
                    + "<div style='border: 1px solid; margin: 10px; padding: 20px; border-radius:25px; "
                    + "text-align:center; background: #ffffff; font-family: Lucida Grande'>"
                    + "<h1>You have no classes now.</h1></div></body></html>");
            this.likeButton.setEnabled(false);
            this.dislikeButton.setEnabled(false);
            this.postComment.setEnabled(false);
            this.jButton1.setEnabled(false);
            this.searchNote.setEnabled(false);
            this.sortChoiceBox.setEnabled(false);
            this.createComment.setEnabled(false);
            return;
        }

        courses = courseList.getCourses();
        // classes dropdown box
        DefaultComboBoxModel dropDownModel = new DefaultComboBoxModel();
        for (Course course : courses) {
            dropDownModel.addElement(course.getCourseName());
        }
        classes.setModel(dropDownModel);
        classes.setToolTipText("Change Class");

        // Posts
        notesOverviewModel = new DefaultListModel<String>();
        currentCourse = courses.get(0);
        displayedNotes = new Vector<>();
        updateNote();
        initPost();
        sortNotes();
    }
    private void initPost() {
        // post Content
        this.post.setText("<html><body style='background-color:#f0f8ff;'>"
                + "<div style='border: 1px solid; margin: 10px; padding: 20px; border-radius:25px; "
                + "text-align:center; background: #ffffff; font-family: Lucida Grande'>"
                + "<h1>Welcome to Notezza!"
                + "<br/>Select a note to view!</h1></div>"
                + "</body></html>");
        this.likeButton.setEnabled(false);
        this.dislikeButton.setEnabled(false);
        this.postComment.setEnabled(false);
        this.createComment.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        functionBar = new javax.swing.JPanel();
        sortChoiceBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchNote = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        classes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lecture = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        viewMember = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overviewList = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        layer2 = new javax.swing.JPanel();
        PostScroll = new javax.swing.JScrollPane();
        post = new javax.swing.JTextPane();
        layer1 = new javax.swing.JPanel();
        likeButton = new javax.swing.JButton();
        dislikeButton = new javax.swing.JButton();
        CommentScroll = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextPane();
        writeCommentPanel = new javax.swing.JPanel();
        createComment = new javax.swing.JTextField();
        postComment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        functionBar.setBackground(new java.awt.Color(99, 172, 229));

        sortChoiceBox.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        sortChoiceBox.setForeground(new java.awt.Color(42, 77, 105));
        sortChoiceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Latest Date", "Highest Rating", "Most Comments", "Most Likes" }));
        sortChoiceBox.addItemListener(this::sortChoiceBoxItemStateChanged);
        //sortChoiceBox.addActionListener(this::sortChoiceBoxActionPerformed);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sort Posts By:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/search-20.png"))); // NOI18N
        jLabel3.setToolTipText("Search Notes");

        searchNote.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        searchNote.setForeground(new java.awt.Color(42, 77, 105));
        searchNote.setText("Search Notes");
        searchNote.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(42, 77, 105), 1, true));
        searchNote.setCaretColor(new java.awt.Color(42, 77, 105));
        searchNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchNoteMouseClicked(evt);
            }
        });
        searchNote.addActionListener(this::searchNoteActionPerformed);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(42, 77, 105));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/plus-17-dark.png"))); // NOI18N
        jButton1.setText("Add New Post");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createNewNote(evt);
            }
        });
        jButton1.setEnabled(client != null);

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        classes.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        classes.setForeground(new java.awt.Color(42, 77, 105));
        classes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        classes.setToolTipText("Change Your Class");
        classes.addItemListener(this::classesItemStateChanged);
//        classes.addActionListener(e -> {
//            initPost();
//            String courseName = (String) classes.getSelectedItem();
//            notesOverviewModel.removeAllElements();
//            overviewList.setModel(notesOverviewModel);
//            for (Course course : courseList.getCourses()) {
//                if (course.getCourseName().equals(courseName)) {
//                    currentCourse = course;
//                    updateNote();
//                    break;
//                }
//            }
//        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/home-20.png"))); // NOI18N

        javax.swing.GroupLayout functionBarLayout = new javax.swing.GroupLayout(functionBar);
        functionBar.setLayout(functionBarLayout);
        functionBarLayout.setHorizontalGroup(
            functionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchNote, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        functionBarLayout.setVerticalGroup(
            functionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(functionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(sortChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jButton1)
                    .addComponent(jSeparator4)
                    .addComponent(classes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Menu.setBackground(new java.awt.Color(75, 134, 180));

        jLabel1.setBackground(new java.awt.Color(144, 201, 229));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 239, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTEZZA");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/logo50.png"))); // NOI18N

        lecture.setBackground(new java.awt.Color(75, 134, 180));
        lecture.setFont(new java.awt.Font("Eurostile", 1, 17)); // NOI18N
        lecture.setForeground(new java.awt.Color(231, 239, 246));
        lecture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecture.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/lecture-20.png"))); // NOI18N
        lecture.setText("Enter Lecture");
        lecture.setToolTipText("");
        lecture.setOpaque(true);
        lecture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectureMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lectureMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lectureMouseEntered(evt);
            }
        });
        lecture.setEnabled(client != null);

        logout.setBackground(new java.awt.Color(75, 134, 180));
        logout.setFont(new java.awt.Font("Eurostile", 1, 17)); // NOI18N
        logout.setForeground(new java.awt.Color(231, 239, 246));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/exit-20.png"))); // NOI18N
        logout.setText("Log Out");
        logout.setToolTipText("");
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });

        profile.setBackground(new java.awt.Color(75, 134, 180));
        profile.setFont(new java.awt.Font("Eurostile", 1, 17)); // NOI18N
        profile.setForeground(new java.awt.Color(231, 239, 246));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/profile-20.png"))); // NOI18N
        profile.setText(" Profile");
        profile.setToolTipText("");
        profile.setOpaque(true);
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
        });
        profile.setEnabled(client != null);

        viewMember.setBackground(new java.awt.Color(75, 134, 180));
        viewMember.setFont(new java.awt.Font("Eurostile", 1, 17)); // NOI18N
        viewMember.setForeground(new java.awt.Color(231, 239, 246));
        viewMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/viewMember-20.png"))); // NOI18N
        viewMember.setText(" Find Classmates");
        viewMember.setToolTipText("");
        viewMember.setOpaque(true);
        viewMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMemberMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMemberMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMemberMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logo)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lecture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMember, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lecture, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel5.setBackground(new java.awt.Color(231, 239, 246));

        overviewList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        overviewList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        overviewList.setCellRenderer(getCellRenderer());
        overviewList.setSelectionBackground(new java.awt.Color(173, 203, 227));
        overviewList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        overviewList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                this.likeButton.setEnabled(true);
                this.dislikeButton.setEnabled(true);
                this.postComment.setEnabled(true);
                this.createComment.setEnabled(true);
                int noteForIndex = overviewList.getSelectedIndex();
                if (noteForIndex < currentCourse.getAllNotes().size() && noteForIndex >= 0) {
                    currentNote = displayedNotes.get(noteForIndex); 
                    displayCurrentNote();
                }
            }
        });
        jScrollPane1.setViewportView(overviewList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel6.setBackground(new java.awt.Color(231, 239, 246));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setOpaque(true);

        PostScroll.setBorder(null);

        post.setEditable(false);
        post.setContentType("text/html"); // NOI18N
        PostScroll.setViewportView(post);

        javax.swing.GroupLayout layer2Layout = new javax.swing.GroupLayout(layer2);
        layer2.setLayout(layer2Layout);
        layer2Layout.setHorizontalGroup(
            layer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
            .addGroup(layer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PostScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
        );
        layer2Layout.setVerticalGroup(
            layer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
            .addGroup(layer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PostScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
        );

        layer1.setOpaque(false);

        likeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/like-22.png"))); // NOI18N
        // TODO HARD CODE
        likeButton.setText("0");
        likeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDisLikeMouseClicked(evt);
            }
        });
        likeButton.setVisible(client != null);
        likeButton.setEnabled(client != null);

        dislikeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/dislike-22.png"))); // NOI18N
        dislikeButton.setText("0");
        dislikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLikeMouseClicked(evt);
            }
        });
        dislikeButton.setVisible(client != null);
        dislikeButton.setEnabled(client != null);

        javax.swing.GroupLayout layer1Layout = new javax.swing.GroupLayout(layer1);
        layer1.setLayout(layer1Layout);
        layer1Layout.setHorizontalGroup(
            layer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layer1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(likeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dislikeButton)
                .addGap(14, 14, 14))
        );
        layer1Layout.setVerticalGroup(
            layer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layer1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(likeButton)
                    .addComponent(dislikeButton))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(layer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(layer1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(layer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(layer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 51, Short.MAX_VALUE)))
        );

        comments.setEditable(false);
        comments.setContentType("text/html"); // NOI18N
        CommentScroll.setViewportView(comments);

        writeCommentPanel.setBackground(new java.awt.Color(231, 239, 246));

        createComment.setToolTipText("Add Comment");
        createComment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        createComment.addActionListener(this::CreateCommentActionPerformed);
        createComment.setEnabled(client != null);

        postComment.setText("Comment");
        postComment.setToolTipText("");
        postComment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	if (currentNote != null) {
            		PostCommentMouseClicked(evt);
            	}
            }
        });
        postComment.setVisible(client != null);
        postComment.setEnabled(client != null);

        javax.swing.GroupLayout writeCommentPanelLayout = new javax.swing.GroupLayout(writeCommentPanel);
        writeCommentPanel.setLayout(writeCommentPanelLayout);
        writeCommentPanelLayout.setHorizontalGroup(
            writeCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(writeCommentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createComment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postComment, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        writeCommentPanelLayout.setVerticalGroup(
            writeCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(writeCommentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(writeCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(writeCommentPanelLayout.createSequentialGroup()
                        .addComponent(postComment)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(createComment))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(writeCommentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CommentScroll, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CommentScroll)
                .addGap(0, 0, 0)
                .addComponent(writeCommentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(functionBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(functionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void createNewNote(MouseEvent evt) {
    	if (client != null) {
    		AddNote addnote = new AddNote(client,currentCourse);
    		addnote.setVisible(true);
    	}
    }

    private void displayCurrentNote() {
        post.setText(Util.getHTMLforNoteDetail(currentNote));
        displayComment();
        likeButton.setText(Integer.toString(currentNote.getNumLikes()));
        dislikeButton.setText(Integer.toString(currentNote.getNumDislikes()));
    }

    private void displayComment() {
        comments.setText(Util.getHTMLforComments(currentNote));
    }

    private void updateNote() {
        notesOverviewModel.removeAllElements();
        displayedNotes = currentCourse.getAllNotes();
        for (Note note : displayedNotes) {
            notesOverviewModel.addElement(Util.getHTMLforNoteOverview(note));
        }
        overviewList.setModel(notesOverviewModel);
    }

    private void AddDisLikeMouseClicked(MouseEvent evt) {
        System.out.println("Adding a like");
        if (client != null) {
        	client.sendCommand(new Command(CommandType.ADD_LIKE, new AddingDislike(client.getUser(),currentNote)));
        }
    }

    private void AddLikeMouseClicked(MouseEvent evt) {
        System.out.println("Adding a dislike...");
        if (client != null) {
	        client.sendCommand(new Command(CommandType.ADD_DISLIKE, new AddingDislike(client.getUser(),currentNote)));
        }
    }

    private void lectureMouseEntered(java.awt.event.MouseEvent evt) {                                     
        lecture.setBackground(new Color(42,77,105));
    }                                    

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {                                    
        logout.setBackground(new Color(42,77,105));
    }                                   

    private void lectureMouseExited(java.awt.event.MouseEvent evt) {                                    
        lecture.setBackground(new Color(75,134,180));
    }                                   

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {                                   
        logout.setBackground(new Color(75,134,180));
    }

    private void lectureMouseClicked(java.awt.event.MouseEvent evt) {
    	if (client != null) {
	        System.out.println("POPPING UP PRESENTATION WINDOW..");
	        if (currentCourse.getCurrentLecture() != null) {
                presentation = new UserPresentation(this.client, currentCourse);
                client.setUserPresentationWindow(presentation);
                presentation.setVisible(true);
            }
    	}
    }

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("GOODBYE");
        System.exit(0);
    }                                   

    private void searchNoteMouseClicked(java.awt.event.MouseEvent evt) {                                        
        searchNote.setText("");
    }                                       

    private void sortChoiceBoxItemStateChanged(java.awt.event.ItemEvent evt) {
        sortNotes();
    }
    
    private void sortNotes() {
        int sortTypeInt = sortChoiceBox.getSelectedIndex();
		displayedNotes = currentCourse.getSortedNotes(SortType.values()[sortTypeInt]);
		refreshList();
    }

    private void refreshList() {
		this.notesOverviewModel = new DefaultListModel<String>();
		for (Note note : displayedNotes) {
			this.notesOverviewModel.addElement(Util.getHTMLforNoteOverview(note));
		}
		this.overviewList.setModel(notesOverviewModel);
    }

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {
        if (client != null) {
	        System.out.println("POPPING UP PROFILES...");
	        UserProfile profile = new UserProfile(client.getUser(), client.getUser());
	        profile.setVisible(true);
        }
    }                                    

    private void profileMouseExited(java.awt.event.MouseEvent evt) {                                    
        profile.setBackground(new Color(75,134,180));
    }                                   

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {                                     
        profile.setBackground(new Color(42,77,105));
    }                                    

    private void viewMemberMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("POPPING UP VIEW ClASSMATES...");
        if (currentCourse != null) {
        	ViewStudentsInClass viewClassMate;
        	if (client != null) {
        		viewClassMate = new ViewStudentsInClass(client.getUser(), currentCourse.getStudents(), currentCourse.getInstructor());
        	} else {
        		viewClassMate = new ViewStudentsInClass(null, currentCourse.getStudents(), currentCourse.getInstructor());
        	}
        	viewClassMate.setVisible(true);
        } else {
            System.out.println("Current course is null");
        }
    }                                       

    private void viewMemberMouseExited(java.awt.event.MouseEvent evt) {                                       
        viewMember.setBackground(new Color(75,134,180));
    }                                      

    private void viewMemberMouseEntered(java.awt.event.MouseEvent evt) {                                        
        viewMember.setBackground(new Color(42,77,105));
    }                                       
//
//    private void sortChoiceBoxActionPerformed(java.awt.event.ActionEvent evt) {
//
//    }

    private void searchNoteActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = this.searchNote.getText();
        displayedNotes = currentCourse.searchNote(keyword);
        this.refreshList();
        System.out.println("Performing search");
    }                                          

    private void classesItemStateChanged(java.awt.event.ItemEvent evt) {
        initPost();
        String courseName = (String) classes.getSelectedItem();
        clearList();
        comments.setText("");
        for (Course course : courseList.getCourses()) {
            if (course.getCourseName().equals(courseName)) {
                currentCourse = course;
                updateNote();
                sortChoiceBox.setSelectedIndex(0);
                break;
            }
        }
    }



    private void clearList() {
        this.notesOverviewModel = (DefaultListModel) overviewList.getModel();
        notesOverviewModel.removeAllElements();
    }

    private void PostCommentMouseClicked(java.awt.event.MouseEvent evt) {
    	if (client != null) {
	        postComment();
    	}
    }


    private void CreateCommentActionPerformed(java.awt.event.ActionEvent evt) {
    	if (client != null) {
	        postComment();
    	}
    }

    private void postComment() {
        System.out.println("post comment clicked...");
        if (!createComment.getText().isEmpty())
        {
            String commentContent = createComment.getText();
            Date date = Util.getCurrentDate();
            User user = client.getUser();
            Comment comment = new Comment(user,commentContent,date,currentNote);
            CourseNoteComment cnc = new CourseNoteComment(currentCourse,currentNote,comment);
            client.sendCommand(new Command(CommandType.ADD_COMMENT,cnc));
        }
        createComment.setText("");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin(null,null).setVisible(true);
            }
        });
    }
    
    private ListCellRenderer<? super String> getCellRenderer() {
        return new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList<?> list,
                    Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                JLabel cellRenderer = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected,cellHasFocus);
                cellRenderer.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0,Color.BLACK));
                return cellRenderer;
            }
        };
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane CommentScroll;
    private javax.swing.JTextPane comments;
    private javax.swing.JTextField createComment;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Menu;
    private javax.swing.JList<String> overviewList;
    private javax.swing.JTextPane post;
    private javax.swing.JButton postComment;
    private javax.swing.JScrollPane PostScroll;
    private javax.swing.JComboBox<String> classes;
    private javax.swing.JButton dislikeButton;
    private javax.swing.JPanel functionBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel layer1;
    private javax.swing.JPanel layer2;
    private javax.swing.JLabel lecture;
    private javax.swing.JButton likeButton;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel profile;
    private javax.swing.JTextField searchNote;
    private javax.swing.JComboBox<String> sortChoiceBox;
    private javax.swing.JLabel viewMember;
    private javax.swing.JPanel writeCommentPanel;
    private UserPresentation presentation;

    public void addComment(Course course, Note note, Comment comment) {
        for (Course courseInList : courseList.getCourses()) {
            System.out.println("Receiving a comment now..");
            System.out.println("Checking courses..");
            if (courseInList.getCourseName().equals(course.getCourseName())) {
                System.out.println("Find course!");
                System.out.println("Checking notes..");
                for (Note noteInSideTheCourse : courseInList.getAllNotes()){
                    if (noteInSideTheCourse.getTitle().equals(note.getTitle())) {
                        System.out.println("Find note!");
                        noteInSideTheCourse.addComment(comment);
                        displayComment();
                        System.out.println("Comment added");
                        return;
                    }
                }
            }
        }
        System.out.println("Adding comment failed");
    }

    public void addNote(Course course, Note note) {
        for (Course courseInList : courseList.getCourses()) {
            System.out.println("Receiving a note now");
            System.out.println("Checking notes...");
            if ( courseInList.getCourseName().equals(course.getCourseName())) {
                System.out.println("Find course!");
                courseInList.addNote(note);
				if (currentCourse.getCourseName().equals(course.getCourseName())) {
					if (this.sortChoiceBox.getSelectedIndex() == 0) {
						sortNotes();
					} else {
						this.sortChoiceBox.setSelectedIndex(0);
					}
				}
                System.out.println("Note added!");
                return;
            }
        }
        System.out.println("Adding note failed");
    }

    public void changePresentation(PresentationANDCourse pc) {
        System.out.println("Changing presentation..");
        Presentation p = pc.getPresentation();
        Course c = pc.getCourse();
        for (Course course : courseList.getCourses()) {
            if (course.getCourseName().equals(c.getCourseName())) {
                course.setCurrentLecture(p);
            }
        }
        if (currentCourse.getCourseName().equals(c.getCourseName())) {
            presentation.setVisible(false);
            presentation = new UserPresentation(this.client,currentCourse);
            client.setUserPresentationWindow(presentation);
            presentation.setVisible(true);
        }

    }


    public void addLike(AddingLike addLike) {
        for (Course courseInList : courseList.getCourses()) {
            System.out.println("Receiving a like note now");
            System.out.println("Checking notes...");
            for (Note note1 : courseInList.getAllNotes()) {
                if (note1.getTitle().equals(addLike.getNote().getTitle())) {
                    note1.addLike(addLike.getUser());
                    if (currentNote.getTitle().equals(note1.getTitle())) {
                        displayCurrentNote();
                    }
                    System.out.println("Like added");
                    return;
                }
            }
        }
        System.out.println("Add like failed");
    }

    public void addDisLike(AddingDislike addDisLike) {
        for (Course courseInList : courseList.getCourses()) {
            System.out.println("Receiving a dislike note now");
            System.out.println("Checking notes...");
            for (Note note1 : courseInList.getAllNotes()) {
                if (note1.getTitle().equals(addDisLike.getNote().getTitle())) {
                    note1.addDislike(addDisLike.getUser());
                    if (currentNote.getTitle().equals(note1.getTitle())) {
                        displayCurrentNote();
                    }
                    System.out.println("DisLike added");
                    return;
                }
            }
        }
        System.out.println("Add like failed");
    }

    // End of variables declaration                   
}
