package NotezzaServer;

public enum CommandType {
    INITIALIZATION_STUDENT,
    INITIALIZATION_INSTRUCTOR,
    LOGIN, // Check with the server if already registered
    LOGIN_FAIL,
    REGISTER,
    REGISTER_DONE,
    CREATE_CLASS,
    UPDATE_CLASS,
    CREATE_PRESENTATION,
    UPDATE_PRESENTATION,
    SEND_CHAT_MESSAGE,
    UPDATE_CHAT,
    ADD_COMMENT,
    UPDATE_COMMENT,
    ADD_NOTE,
    UPDATE_NOTE,
    ADD_LIKE,
    ADD_DISLIKE,
    SEND_QUIZ,
    UPDATE_QUIZ,
    UPDATE_LIKE,
    UPDATE_DISLIKE;
}
